### ISSUE TITLE
Needs Ruby >= 2.5?

### ISSUE THREAD

**Issue by andyw8** [testdouble/referral#2]
```
% ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin16]
% referral
~/.rvm/gems/ruby-2.4.4/gems/referral-0.0.1/lib/referral/value/result.rb:3:in `new': {:keyword_init=>true} is not a symbol (TypeError)
```

https://blog.bigbinary.com/2018/01/16/ruby-2-5-allows-creating-structs-with-keyword-arguments.html

**Comment by searls** [comment]
As mentioned on the README, referral must be run on Ruby 2.6 or later due to its dependency on [RubyVM::AbstractSyntaxTree](https://ruby-doc.org/core-2.6.3/RubyVM/AbstractSyntaxTree.html)

I chose not to enforce this in the gemspec, because I didn't want to hold people up from adding referral to their Gemfiles and locking its version as a dependency, since so many projects run multiple Ruby versions from a single Gemfile and will only ever run referral as  CLI.

I just cut referral@0.0.2 which cleans this up, making it safe to `require "referral"` for Rubies at least as old as 2.1.0 and which prints this message if the CLI is invoked:

```
Error: referral must be run with Ruby 2.6 or later, but this is #{RUBY_VERSION}.
       You can often analyze older Ruby code by running this CLI with a newer
       Ruby than the code being inspected.

       Tools like rbenv may help you manage this issue. If you install
       referral into a supported Ruby, you can specify that it be run with
       an environment variable, even if the current directory is locked
       to an older version of Ruby. Just specify the Ruby you want to use:

       RBENV_VERSION=2.6.3 referral
```

**Comment by andyw8** [comment]
👍 thanks for the quick fix.
